cart/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
 
urlpatterns = [
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('', views.cart_detail, name='cart_detail'),
    path('stock/',views.decrementarStock, name='decrementarStock'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from config import settings
from Cavovich.views import *


from django.conf import settings
from django.conf.urls import url, include
from cart import *
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),

    path('cart/',include(('cart.urls', 'cart'), namespace='cart')),

    path('usuarios/', loginUsuarios, name='usuarios'),
    path('login/', loginLogin, name='login'),
    path('signin/', loginSignin, name='signin'),
    path('logout/', loginLogout, name='logout'),
    path('password/', loginPassword, name='password'),

    path('', vinos, name='inicio'),
    path('vino/agregar/', agregarVino, name='agregarVino'),
    path('vino/', VinoCreate.as_view(), name='crearVino'),
    path('vino/<int:pk>', DetalleVino.as_view()),
    path('vino/update/<int:pk>/', VinoUpdate.as_view()),
    path('vino/delete/<int:pk>/', VinoDelete.as_view()),
    path('vino/stock/', incrementarStockVino, name='incrementarStock'),    

    path('bodega/', BodegaList.as_view(), name='verBodega'),
    path('bodega/create/', BodegaCreate.as_view()),
    path('bodega/update/<int:pk>/', BodegaUpdate.as_view()),
    path('bodega/delete/<int:pk>/', BodegaDelete.as_view()),

    path('origen/', OrigenList.as_view(), name='verOrigen'),
    path('origen/create/', OrigenCreate.as_view()),
    path('origen/update/<int:pk>/', OrigenUpdate.as_view()),
    path('origen/delete/<int:pk>/', OrigenDelete.as_view()),

    path('variedad/', VariedadList.as_view(), name='verVariedad'),
    path('variedad/create/', VariedadCreate.as_view()),
    path('variedad/update/<int:pk>/', VariedadUpdate.as_view()),
    path('variedad/delete/<int:pk>/', VariedadDelete.as_view()),

    path('estante/', EstanteList.as_view(), name='verEstantes'),
    path('estante/create/', EstanteCreate.as_view()),
    path('estante/update/<int:pk>/', EstanteUpdate.as_view()),
    path('estante/delete/<int:pk>/', EstanteDelete.as_view()),

    # path('comentario/create/', ComentarioCreate.as_view()),
    # path('comentario/update/<int:pk>/', ComentarioUpdate.as_view()),
    # path('comentario/delete/<int:pk>/', ComentarioDelete.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from  django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'number',
        }))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.conf import settings
 
#from shop.models import Product
from Cavovich.models import Vino
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Vino, pk=product_id)
    cart.add(product=product, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Vino, pk=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

def decrementarStock(request):
    if not request.user.is_authenticated:
        return redirect('login')
    cart = Cart(request)
    for item in cart:
        print(item)
        item['product'].stock(item['quantity'])
    cart.clear()
    cart = {}
    return redirect('/')

templates/cart/detail.html
{% extends 'cavovich/baseIndex.html' %} 
{% load static %}
 
 
{% block content %}
<main role="main ">   
    <div class="bg-light">
        <br>        
        <div class="container card bg-white">   
            <div class="col-12">
                <br>
                <h1>Tu carrito</h1>     
                <br>           
                <div class="table-responsive">            
                    <table class="table table-hover" style="width: 100%">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Imagen</th>
                            <th scope="col">Producto</th>
                            <th scope="col">Unidades</th>
                            <th scope="col">Eliminar</th>
                            <th scope="col">P. unitario</th>
                            <th scope="col">Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                                <tr>
                                    <td>
                                        <a href="/vino/{{product.id}}">
                                            <img src="{{ product.imagen.url }}" width="50px">
                                        </a>
                                    </td>
                                    <td>{{ product.nombre }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>
                                        <a href="{% url "cart:cart_remove" product.id %}"><p class="text-muted"><i class="fas fa-pen"></i> Eliminar</p></a>
                                    </td>
                                    <td class="num">${{ item.price }}</td>
                                    <td class="num">${{ item.total_price }}</td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                        <tr class="total">
                            <td>Total</td>
                            <td colspan="4"></td>
                            <td class="num">${{ cart.get_total_price }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            
            <p class="text-right">
                <a href="{% url "inicio" %}" class="btn btn-secondary"><i class="fas fa-shopping-cart"></i> Seguir buscando</a>
                <form action="{% url 'cart:decrementarStock' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Finalizar</button>
                </form>
            </p>

            <br>
            </div>
        </div>
        <br>
    </div>
</div>    
{% endblock %}