cart/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
 
urlpatterns = [
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('', views.cart_detail, name='cart_detail'),
    path('stock/',views.decrementarStock, name='decrementarStock'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from config import settings
from Cavovich.views import *


from django.conf import settings
from django.conf.urls import url, include
from cart import *
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),

    path('cart/',include(('cart.urls', 'cart'), namespace='cart')),

    path('usuarios/', loginUsuarios, name='usuarios'),
    path('login/', loginLogin, name='login'),
    path('signin/', loginSignin, name='signin'),
    path('logout/', loginLogout, name='logout'),
    path('password/', loginPassword, name='password'),

    path('', vinos, name='inicio'),
    path('vino/agregar/', agregarVino, name='agregarVino'),
    path('vino/', VinoCreate.as_view(), name='crearVino'),
    path('vino/<int:pk>', DetalleVino.as_view()),
    path('vino/update/<int:pk>/', VinoUpdate.as_view()),
    path('vino/delete/<int:pk>/', VinoDelete.as_view()),
    path('vino/stock/', incrementarStockVino, name='incrementarStock'),    

    path('bodega/', BodegaList.as_view(), name='verBodega'),
    path('bodega/create/', BodegaCreate.as_view()),
    path('bodega/update/<int:pk>/', BodegaUpdate.as_view()),
    path('bodega/delete/<int:pk>/', BodegaDelete.as_view()),

    path('origen/', OrigenList.as_view(), name='verOrigen'),
    path('origen/create/', OrigenCreate.as_view()),
    path('origen/update/<int:pk>/', OrigenUpdate.as_view()),
    path('origen/delete/<int:pk>/', OrigenDelete.as_view()),

    path('variedad/', VariedadList.as_view(), name='verVariedad'),
    path('variedad/create/', VariedadCreate.as_view()),
    path('variedad/update/<int:pk>/', VariedadUpdate.as_view()),
    path('variedad/delete/<int:pk>/', VariedadDelete.as_view()),

    path('estante/', EstanteList.as_view(), name='verEstantes'),
    path('estante/create/', EstanteCreate.as_view()),
    path('estante/update/<int:pk>/', EstanteUpdate.as_view()),
    path('estante/delete/<int:pk>/', EstanteDelete.as_view()),

    # path('comentario/create/', ComentarioCreate.as_view()),
    # path('comentario/update/<int:pk>/', ComentarioUpdate.as_view()),
    # path('comentario/delete/<int:pk>/', ComentarioDelete.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Cavovich/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE, PROTECT
from django.db.models.fields.related import OneToOneField
from django.utils.html import format_html

# Create your models here.

class Estante(models.Model):
    estante = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.estante

class Variedad(models.Model):
    variedad = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.variedad

class Origen(models.Model):
    origen = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.origen

class Bodega(models.Model):
    bodega = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.bodega

class Vino(models.Model):
    nombre = models.CharField(max_length=100)
    bodega = models.ForeignKey(Bodega, on_delete=CASCADE)
    variedad = models.ForeignKey(Variedad, on_delete=CASCADE)
    cosecha = models.PositiveSmallIntegerField()
    origen = models.ForeignKey(Origen, on_delete=CASCADE)
    cantidad = models.PositiveSmallIntegerField()
    codigo = models.BigIntegerField()
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    estante = models.ForeignKey(Estante, on_delete=CASCADE)
    imagen = models.ImageField(upload_to="catalogo/", default='catalogo/default.png') #se van a guardar en media/catalogo

    def stock(this, cantidad):
        this.cantidad -= cantidad
        this.save()
    
    def incrementarStock(self, cantidad):
        self.cantidad += cantidad
        self.save()

class Comentario(models.Model):
    ojo = models.PositiveSmallIntegerField()
    nariz = models.PositiveSmallIntegerField()
    boca = models.PositiveSmallIntegerField()
    equilibrio_armonia = models.PositiveSmallIntegerField()
    nota = models.TextField()
    vino = OneToOneField(Vino,on_delete=PROTECT)

Cavovich/forms.py
from django import forms
from django.forms import fields
from django.forms.models import ModelForm
from .models import Comentario, Vino, Bodega, Origen, Variedad, Estante

class VinoForm(forms.ModelForm):
    # nombre = forms.CharField(widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'type': 'text'
    #     }))
    # bodega = forms.CharField(widget=forms.Select(choices=Bodega.objects.all().values_list(),attrs={
    #     'class': 'form-control'
    # }))
    # variedad = forms.CharField(widget=forms.Select(choices=Variedad.objects.all().values_list() ,attrs={
    #     'class': 'form-control'
    # }))
    # cosecha = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type': 'date'
    # }))
    # origen = forms.CharField(widget=forms.Select(choices=Origen.objects.all().values_list() ,attrs={
    #     'class': 'form-control'
    # }))
    # cantidad = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type': 'number'
    # }))
    # codigo = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type': 'number'
    # }))
    # precio = forms.CharField(widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'type': 'number'
    # }))
    # estante = forms.CharField(widget=forms.Select(choices=Estante.objects.all().values_list() ,attrs={
    #     'class': 'form-control'
    # }))

    class Meta:
        model = Vino
        fields = '__all__'
        
        

class BodegaForm(forms.ModelForm):
    class Meta:
        model = Bodega
        fields = '__all__'

class OrigenForm(forms.ModelForm):
    class Meta:
        model = Origen
        fields = '__all__'

class VariedadForm(forms.ModelForm):
    class Meta:
        model = Variedad
        fields = '__all__'

class EstanteForm(forms.ModelForm):
    class Meta:
        model = Estante
        fields = '__all__'

class ComentarioForm(forms.ModelForm):

    # def __init__(self, *args, **kwargs):
    #     super(ModelForm, self).__init__(**args, **kwargs)
    #     for visible in self.visible_fields():
    #         if visible.field.name == campps:
    #             visible.field.widget.attr['class'] = 'tu_clase'


    class Meta:
        model = Comentario
        fields = '__all__'

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input100',
        'type': 'text'
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'input100',
        'type': 'password'
    }))

class PasswordForm(forms.Form):
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Contraseña',
        'type': 'password'
    }))

Cavovich/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, TemplateView, FormView, CreateView, DetailView, UpdateView, DeleteView
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import EmptyQuerySet

from .models import Bodega, Comentario, Estante, Origen, Variedad, Vino
from .forms import VinoForm, BodegaForm, OrigenForm, VariedadForm, EstanteForm, ComentarioForm, LoginForm, PasswordForm

from cart.forms import CartAddProductForm

# Create your views here.

#Crea el agregar al carrito
def product_detail(request, id):
    vino = get_object_or_404(Vino, pk=id, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'cavovich/wine.html', {'vino': vino, 'cart_product_form': cart_product_form})

#Login
def loginUsuarios(request):
    return render(request, 'cavovich/login_list.html')

def loginLogin(request):
    forms = LoginForm()
    if request.method == 'POST':
        forms = LoginForm(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Usuario o Contraseña no son validos')
    context = {'form': forms}
    return render(request, 'cavovich/login.html', context)

def loginSignin(request):
    if not request.user.is_authenticated:
        return redirect('login')
    forms = LoginForm()
    if request.method == 'POST':
        forms = LoginForm(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            user = User.objects.create_user(username, 'pordefecto@mail.com', password)
            if user:
                return redirect('/')
    context = {'form': forms}
    return render(request, 'cavovich/signin.html', context)

def loginPassword(request):
    forms = PasswordForm()
    if request.method == 'POST':
        forms = PasswordForm(request.POST)
        if forms.is_valid():
            if request.user.is_authenticated:
                #password_old = forms.cleaned_data['password_old']
                password_new = forms.cleaned_data['password']
                username = request.user.username
                user = User.objects.get(username=username)
                user.set_password(password_new)
                user.save()
                #messages.success(request, 'Cambio de contraseña con exito')
                return redirect("/")
            else:
                messages.warning(request, 'No esta iniciado sesion')
    context = {'form': forms}
    return render(request, 'cavovich/password.html', context)

def loginLogout(request):
    logout(request)
    return redirect('/')

#Vino:
def vinos(request): #Listar (opcion para buscar)
    if request.method == 'GET':
        search = request.GET.get('search')
        if search == None:
            all_vinos = Vino.objects.all().order_by('nombre')
            return render(request, 'cavovich/index.html', {'vinos_list':all_vinos, 'buscador':''})
        else:
            vinos_list_nombre = Vino.objects.filter(nombre__contains = search)
            vinos_list_bodega = Vino.objects.filter(bodega__bodega__contains = search)
            vinos_list_variedad = Vino.objects.filter(variedad__variedad__contains = search)
            vinos_list_cosecha = Vino.objects.filter(cosecha__contains = search)
            vinos_list_origen = Vino.objects.filter(origen__origen__contains = search)
            vinos_list_codigo = Vino.objects.filter(codigo__contains = search)
            vinos_list_estante = Vino.objects.filter(estante__estante__contains = search)
            vinos_list = vinos_list_nombre.union(vinos_list_bodega, vinos_list_variedad, vinos_list_cosecha, vinos_list_origen, vinos_list_codigo, vinos_list_estante).order_by('nombre')
            return render(request, 'cavovich/index.html', {'vinos_list':vinos_list, 'buscador': search})

class DetalleVino(DetailView): #vino por ID:
    model = Vino
    template_name = 'cavovich/wine.html'
    context_object_name = 'vino'

def agregarVino(request):
    codigo_barras = request.GET.get('codigo_barras')
    if codigo_barras != None:
        vino = Vino.objects.filter(codigo = codigo_barras) 
        if vino.exists():
            return render(request, 'cavovich/incrementar.html', {'vino':vino.first()})
        else:
            return redirect('/vino/') #Falta autocompletar el valor del codigo de barras.

    return render(request, 'cavovich/agregar.html')

def incrementarStockVino(request):
    cantidad = int(request.GET.get('cantidad'))
    vinoId = request.GET.get('vinoId')
    if cantidad != None and vinoId != None:
        vino = Vino.objects.filter(id = vinoId).first()
        vino.incrementarStock(cantidad)
        print(f"vino: {vino}")
    return redirect('/')

class VinoCreate(LoginRequiredMixin, CreateView): #Crear
    login_url = 'login'
    model = Vino
    template_name = 'cavovich/vino.html'
    form_class = VinoForm
    success_url = "/"

class VinoUpdate(LoginRequiredMixin, UpdateView): #Modificar
    login_url = 'login'
    model = Vino
    template_name = 'cavovich/vino.html'
    form_class = VinoForm
    success_url = "/"

class VinoDelete(LoginRequiredMixin, DeleteView): #Eliminar
    login_url = 'login'
    model = Vino
    template_name = 'cavovich/eliminar.html'
    form_class = VinoForm
    success_url = "/"
    
#Bodega:
class BodegaList(LoginRequiredMixin, ListView): #Listar
    login_url = 'login'
    model = Bodega
    template_name = 'cavovich/bodega_list.html'
    context_object_name = 'bodegas_list'

class BodegaCreate(LoginRequiredMixin, CreateView): #Crear
    login_url = 'login'
    model = Bodega
    template_name = 'cavovich/bodega.html'
    form_class = BodegaForm
    success_url = "/bodega"

class BodegaUpdate(LoginRequiredMixin, UpdateView): #Modificar
    login_url = 'login'
    model = Bodega
    template_name = 'cavovich/bodega.html'
    form_class = BodegaForm
    success_url = "/bodega"

class BodegaDelete(LoginRequiredMixin, DeleteView): #Eliminar
    login_url = 'login'
    model = Bodega
    template_name = 'cavovich/eliminar.html'
    form_class = BodegaForm
    success_url = "/bodega"

#Origen:
class OrigenList(LoginRequiredMixin, ListView): #Listar
    login_url = 'login'
    model = Origen
    template_name = 'cavovich/origen_list.html'
    context_object_name = 'origen_list'

class OrigenCreate(LoginRequiredMixin, CreateView): #Crear
    login_url = 'login'
    model = Origen
    template_name = 'cavovich/origen.html'
    form_class = OrigenForm
    success_url = "/origen"

class OrigenUpdate(LoginRequiredMixin, UpdateView): #Modificar
    login_url = 'login'
    model = Origen
    template_name = 'cavovich/origen.html'
    form_class = OrigenForm
    success_url = "/origen"

class OrigenDelete(LoginRequiredMixin, DeleteView): #Eliminar
    login_url = 'login'
    model = Origen
    template_name = 'cavovich/eliminar.html'
    form_class = OrigenForm
    success_url = "/origen"

#Variedad:
class VariedadList(LoginRequiredMixin, ListView): #Listar
    login_url = 'login'
    model = Variedad
    template_name = 'cavovich/variedad_list.html'
    context_object_name = 'variedad_list'

class VariedadCreate(LoginRequiredMixin, CreateView): #Crear
    login_url = 'login'
    model = Variedad
    template_name = 'cavovich/variedad.html'
    form_class = VariedadForm
    success_url = "/variedad"

class VariedadUpdate(LoginRequiredMixin, UpdateView): #Modificar
    login_url = 'login'
    model = Variedad
    template_name = 'cavovich/variedad.html'
    form_class = VariedadForm
    success_url = "/variedad"

class VariedadDelete(LoginRequiredMixin, DeleteView): #Eliminar
    login_url = 'login'
    model = Variedad
    template_name = 'cavovich/eliminar.html'
    form_class = VariedadForm
    success_url = "/variedad"

#Estante:
class EstanteList(LoginRequiredMixin, ListView): #Listar
    login_url = 'login'
    model = Estante
    template_name = 'cavovich/estantes_list.html'
    context_object_name = 'estantes_list'

class EstanteCreate(LoginRequiredMixin, CreateView): #Crear
    login_url = 'login'
    model = Estante
    template_name = 'cavovich/estante.html'
    form_class = EstanteForm
    success_url = "/estante"

class EstanteUpdate(LoginRequiredMixin, UpdateView): #Modificar
    login_url = 'login'
    model = Estante
    template_name = 'cavovich/estante.html'
    form_class = EstanteForm
    success_url = "/estante"

class EstanteDelete(LoginRequiredMixin, DeleteView): #Eliminar
    login_url = 'login'
    model = Estante
    template_name = 'cavovich/eliminar.html'
    form_class = EstanteForm
    success_url = "/estante"

#Comentario:
# class ComentarioCreate(CreateView): #Crear
#     model = Comentario
#     template_name = 'cavovich/comentario.html'
#     form_class = ComentarioForm
#     success_url = "/"

# class ComentarioUpdate(UpdateView): #Modificar
#     model = Comentario
#     template_name = 'cavovich/comentario.html'
#     form_class = ComentarioForm
#     success_url = "/"

# class ComentarioDelete(DeleteView): #Eliminar
#     model = Comentario
#     template_name = 'cavovich/eliminar.html'
#     form_class = ComentarioForm
#     success_url = "/"

templates/cavovich/bodega.html
{% extends 'cavovich/baseIndex.html' %} 

{% block content %} 
{% load static %}
<main role="main" class="bg-white">
    <br>
    <div class="card">
        <div class="card-header">                
            <div class="d-flex justify-content-between">
                <div>
                    <h4 >Nueva bodega</h4>
                </div>
                <div>                   
                </div>
            </div>            
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row mb-3">
                  <label for="inputEmail3" class="col-sm-2 col-form-label">Nombre</label>
                  <div class="col-sm-10">
                    {{ form.bodega }}
                  </div>
                </div>     
                <div class="d-flex justify-content-between">
                    <div>                                              
                    </div>
                    <div>
                        <a href="{% url 'inicio' %}">
                            <input type="button" class="btn btn-danger float-right" value="Cancelar" >
                        </a>  
                        <button type="submit" class="btn btn-primary ">Guardar cambios</button>
                    </div>
                </div>           
            </form>
        </div>
    </div>
    <br> 
</main> 
{% endblock %}

templates/cavovich/incrementar.html
{% extends 'cavovich/baseIndex.html' %} 

{% block content %} 
{% load static %}

<form action="{% url 'incrementarStock' %}" method="get">
    {% csrf_token %}
    <h1>Datos del vino:</h1> <!-- Mostrar datos del vino lindo (para que el usuario sepa cual vino esta modificando)-->
    <h2>Nombre: {{vino.nombre}}</h2>
    <h2>Cantidad actual: {{vino.cantidad}}</h2>
    <p>Cantidad para agregar: </p>
    <input type="number" name="cantidad" min="0" required="" id="id_cantidad">

    <input hidden type="number" name="vinoId" value="{{vino.id}}" readonly> <!--Se puede poner como oculto o podemos usar el codigo de barras (me parece mejor usar el ID)-->

    <button class="btn btn-primary">Incrementar</button>
</form>


{% endblock %}

templates/cavovich/login_list.html
{% extends 'cavovich/baseIndex.html' %} 

{% block content %} 
{% load static %}

<a href="{% url 'signin' %}">Registrarse</a> <br>
<a href="{% url 'login' %}">Login</a> <br>
<a href="{% url 'password' %}">Cambiar Contraseña</a> <br>
<a href="{% url 'logout' %}">Logout</a> <br>


{% endblock %}

templates/cavovich/vino.html
{% extends 'cavovich/baseIndex.html' %} 

{% block content %} 
{% load static %}

<main role="main ">   

    <div class="bg-light">
        <br>
        <div class="container card bg-white">   
            <div class="card-body">
                <h4 class="card-title">Crear/modificar Vino</h5><br>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% comment %} {{ form.as_p }} {% endcomment %}   
                    <div class="row mb-3">
                        <label for="id_nombre" class="col-sm-2 col-form-label">Nombre:</label>
                        <div class="col-sm-10">
                            {{ form.nombre }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Bodega:</label>
                        <div class="col-sm-10">
                            {{ form.bodega }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Variedad:</label>
                        <div class="col-sm-10">
                            {{ form.variedad }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Cosecha:</label>
                        <div class="col-sm-10">
                            {{ form.cosecha }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Origen:</label>
                        <div class="col-sm-10">
                            {{ form.origen }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Cantidad:</label>
                        <div class="col-sm-10">
                            {{ form.cantidad}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Código:</label>
                        <div class="col-sm-10">
                            {{ form.codigo }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Precio:</label>
                        <div class="col-sm-10">
                            {{ form.precio }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Estante:</label>
                        <div class="col-sm-10">
                            {{ form.estante }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="id_bodega" class="col-sm-2 col-form-label">Imagen:</label>
                        <div class="col-sm-10">
                            {{ form.imagen }}
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="d-flex justify-content-between">
                            <div>                                              
                            </div>
                            <div>
                                <input type="submit" class="btn btn-primary" value="Guardar">
                                <a href="{% url 'inicio' %}">
                                    <input type="button" class="btn btn-danger float-right" value="Cancelar" >
                                </a>
                            </div>
                        </div>  
                        
                    </div>                    
                </form>
            </div>
        </div>
        <br>
    </div>   
</main> 
{% endblock %}

templates/cavovich/wine.html
{% extends 'cavovich/baseIndex.html' %} 

{% block content %} 
{% load static %}
<main role="main ">   
    <style>
        {% comment %} .card-img{
            width:630px;
            height:380px;
            overflow:hidden;
          }

        .card-img img{
            width:100%;
            height:auto
          } {% endcomment %}
    </style>
    <div class="bg-light">
        <br>
        <div class="container card bg-white" style="max-width: 1200px; min-height: 700px;"> 
            <div class="d-flex justify-content-between">
                <div>
                   
                </div>
                <div>
                    <br>
                    <a style="cursor: pointer;" onclick="window.location='/vino/update/{{vino.pk}}';"> 
                        <div class="text-muted">
                            <i class="fas fa-edit"></i> Modificar
                        </div>
                    </a>
                    <a style="cursor: pointer;" onclick="window.location='/vino/delete/{{vino.pk}}';"> 
                        <div class="text-muted">
                            <i class="fas fa-trash"></i> Eliminar
                        </div>
                    </a>  
                </div>
           </div> 
            <div class="row">
                <div class="col-md-4">                    
                    <!-- Imagen del producto -->
                    <div class="card-img">
                        <img src="/media/{{vino.imagen}}"  class="img-fluid rounded-start">
                    </div>              
                </div>        
                <div class="col-md-8 card-body">                                            
                    <br>
                    <div class="row">
                        <div class="col-12">
                            <h2 class="card-title">
                                {{vino.nombre}}                                    
                            </h1>           
                            <h6 class="card-subtitle mb-2 text-muted">
                                {% if vino.cantidad > 0 %}
                                    <span class="badge bg-success">Stock</span>
                                {% else %}
                                    <span class="badge bg-danger">Sin Stock</span>
                                {% endif %}
                            </h6>                     
                        </div>
                    </div>                            
                    <div class="form-group row">
                        <div class="col-sm-8 col-md-9">
                            <h1 class="card-title">USD $ {{vino.precio}}</span>
                        </div>
                    </div>                  
                    <!-- Detalle del producto  -->             
                    <div class="form-group row">
                        <label class="col-sm-3 col-md-3 form-control-label text-muted"><b>Bodega:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.bodega}}</p>
                        </div>
                    </div>                         
                    <div class="form-group row">
                        <label class="col-sm-3 col-md-3 text-muted"><b>Variedad:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.variedad}}</p>
                        </div>
                    </div> 
                    <div class="form-group row">
                        <label class="col-sm-3 col-md-3 form-control-label text-muted"><b>Cosecha:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.cosecha}}</p>
                        </div>
                    </div> 
                    <div class="form-group row">
                        <label class="col-sm-3 col-md-3 form-control-label text-muted"><b>Origen:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.origen}}</p>
                        </div>
                    </div> 
                    <div class="form-group row">
                        <label class="col-sm-3 col-md-3 form-control-label text-muted"><b>Codigo:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.codigo}}</p>
                        </div>
                    </div> 
                    <div class="form-group row">
                        <label class="col-sm-3 col-md-3 form-control-label text-muted"><b>Estante:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.estante}}</p>
                        </div>
                    </div>                     
                    <div class="form-group row">
                        <label for="Quantity" class="col-sm-3 col-md-3 form-control-label text-muted"><b>Cantidad:</b></label>
                        <div class="col-sm-9 col-md-9">
                            <p class="card-text">{{vino.cantidad}}</p>                            
                        </div>
                    </div>
                    <form class="form-horizontal" action="{% url "cart:cart_add" vino.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <div class="form-group product-stock product-available row visible">
                            <label class="col-sm-3 col-md-3 form-control-label"></label>
                            <div class="col-sm-8 col-sm-offset-3 col-md-9 col-md-offset-3">
                                {% if vino.cantidad > 0 %}
                                    <button type="submit" class="btn btn-primary my-2" >
                                        <i class="fas fa-shopping-cart"></i> Añadir al carrito
                                    </button>                                        
                                {% else %}
                                    <button type="submit" class="btn btn-primary my-2" disabled>
                                        <i class="fas fa-shopping-cart"></i> Añadir al carrito
                                    </button>
                                {% endif %}   
                                <a href="javascript:history.back()" class="btn btn-link btn-sm" title="Continue Shopping">← Regresar</a>
                            </div>
                        </div>
                    </form>
                    <script>
                        $('#product-sharing a').click(function(){
                            return !window.open(this.href, 'Share', 'width=640,height=300');
                        });
                    </script> 
                </div>
            </div>  
        </div>
        <br>
    </div>    
</main>
{% endblock %}